[metadata]
name = convert-to-xsd
version = 0.1.1
description = Convert JSON plano para XSD/XML
long_description = file: README.md
long_description_content_type = text/markdown
author = Paulo Freitas
author_email = paulosfjunior@gmail.com
owner = Tooark
license = MIT
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
py_modules = convert
install_requires = lxml
python_requires = >=3.8

[options.entry_points]
console_scripts =
    convert-to-xsd = convert:main
